show/urls.py
from django.conf.urls import url
from . import views
from django.views import View
from show.views import *

app_name = 'show'
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/(\d+)/$', views.profile, name='profile'),
    url(r'^watchlist/(\d+)/$', views.watchlist, name='watchlist'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^addRating/$', views.addRating, name='addRating'),
    url(r'^watchlist-delete/(?P<pk>[0-9]+)/$', WatchlistDeleteView.as_view(), name='watchlist_delete'),
    url(r'^watchlist-complete/(\d+)/$', views.WatchlistCompView, name='watchlist_comp'),
    url(r'^watchlist-add/(\d+)/$', views.watch_list_add, name='watch_list_add'),
    url(r'^add_rate/(\d+)/$', views.add_rate, name='add_rate'),
]

tvseries/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('show.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

show/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator


class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='profile')
    photo = models.ImageField(upload_to='users', blank=True, null=True)
    gender = models.CharField(max_length=6, blank=True, null=True)
    interests = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return str(self.user)


class TVseries(models.Model):
    name = models.CharField(max_length = 100, default=None)

    def __str__(self):
        return self.name


class SeriesRating(models.Model):
    series = models.ForeignKey(TVseries, on_delete=models.CASCADE, related_name='series')
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='userprofile')
    rating = models.PositiveIntegerField(validators=[MaxValueValidator(10)], null=True, blank=True)
    def __str__(self):
        return str(self.series)

class Watchlist(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='watchlist_user')
    series = models.ForeignKey(TVseries, on_delete=models.CASCADE, related_name='watchlist_series')
    status = models.CharField(max_length=50, blank=True, null=True, default="pending")
    percent = models.PositiveIntegerField(validators=[MaxValueValidator(100)], null=True, blank=True)

show/views.py
from django.shortcuts import render
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.shortcuts import redirect
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import *
from recombee_api_client.api_client import RecombeeClient
from recombee_api_client.exceptions import APIException
from recombee_api_client.api_requests import *
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView

client = RecombeeClient('tvseries', 'IG1t5vSWYgpJvClpbJZUn29oqnCu6QnIHoJdm9u5dRLom47i0WrpWrNKcZ9om21x')

def homepage(request):
    return render(request, './show/index.html')


def login(request):
    if request.user.is_authenticated:
        redirect_url = '/profile/' + str(request.user.id)
        return HttpResponseRedirect(redirect_url)
    else:
        if request.method == 'POST':
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    redirect_url = '/profile/' + str(user.id)
                    auth_login(request, user)
                    return HttpResponseRedirect(redirect_url)
                else:
                    error = 'Your account is disabled.'
                    return render(request, './show/login.html', {'error': error})
            else:
                error = 'Incorrect Username or Password'
                return render(request, './show/login.html', {'error': error})
        else:
            return render(request, './show/login.html', {})


def logout(request):
    auth_logout(request)
    return redirect(reverse('show:login'))


def register(request):
    if request.user.is_authenticated:
        redirect_url = '/profile/' + str(request.user.id)
        return HttpResponseRedirect(redirect_url)
    else:
        if request.method == 'POST':
            username = request.POST.get('username', '')
            password = request.POST.get('password', '')
            email = request.POST.get('email', '')
            first_name = request.POST.get('fname', '')
            last_name = request.POST.get('lname', '')

            if User.objects.filter(username=username).exists():
                error = 'The Sap_id is already in use by another account.'
                return render(request, './show/register.html', {'error': error})

            else:
                user = User.objects.create_user(username=username, email=email,first_name=first_name,last_name=last_name)
                user.set_password(password)
                user.save()
                profile = UserProfile.objects.create(user=user)
                profile.save()
                redirect_url = '/profile/' + str(user.id)
                auth_login(request, user)
                return HttpResponseRedirect(redirect_url)
        else:
            return render(request, './show/register.html')


@login_required
def profile(request,id):
    id = int(id)
    if id == request.user.id:
        if request.method == 'POST':
            username = request.POST.get('username', '')
            email = request.POST.get('email', '')
            first_name = request.POST.get('fname', '')
            last_name = request.POST.get('lname', '')
            gender = request.POST.get('gender', '')
            interests = request.POST.get('interests', '')
            user = User.objects.get(id=id)
            profile = UserProfile.objects.get(user=user)
            user.username = username
            user.email = email
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            profile.gender = gender
            profile.interests = interests
            profile.save()
            return render(request, './show/profile.html',{'profile':profile,'user':user})
        else:
            user = User.objects.get(id=id)
            profile = UserProfile.objects.get(user=user)
            return render(request, './show/profile.html',{'profile':profile,'user':user})
    else:
        user = request.user
        profile = UserProfile.objects.get(user=user)
        redirect_url = '/profile/' + str(user.id)
        return HttpResponseRedirect(redirect_url)


@login_required
def watchlist(request,id):
    id = int(id)
    if id == request.user.id:
        user = User.objects.get(id=id)
        profile = UserProfile.objects.get(user=user)
        watch_list = Watchlist.objects.filter(user=profile)
        return render(request, './show/watchlist.html',{'watch_list':watch_list,'id':id})
    else:
        user = request.user
        profile = UserProfile.objects.get(user=user)
        redirect_url = '/watchlist/' + str(user.id)
        return HttpResponseRedirect(redirect_url)

class WatchlistDeleteView(DeleteView):
    login_url = '/login/'
    model = Watchlist
    success_url = '/watchlist/'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        success_url = success_url + str(self.request.user.id)
        print(self.object)
        self.object.delete()
        return HttpResponseRedirect(success_url)

@login_required
def WatchlistCompView(request,id):
    user = request.user
    obj = Watchlist.objects.get(id=id)
    obj.status = "Completed"
    obj.percent = 100
    obj.save()
    success_url = '/watchlist/' + str(request.user.id)
    return HttpResponseRedirect(success_url)

@login_required
def dashboard(request):
    if request.method == 'POST':
        print('okay')
    recommend = client.send(RecommendItemsToUser(request.user.id, 9))
    recommend = recommend["recomms"]
    print(recommend)
    list1 = []
    for i in range(0,len(recommend)):
        print(int(recommend[i]['id']))
        print(recommend[i])
        list1.append(TVseries.objects.get(id=int(recommend[i]['id'])))
    return render(request, './show/dashboard.html', {'recommend': list1})


@login_required
def addRating(request):
    tvseries = TVseries.objects.all()[0:30]
    print(tvseries)
    return render(request, './show/addRating.html', {'tvseries': tvseries})


@login_required
def watch_list_add(request,id):
    tvseries = TVseries.objects.get(id=id)
    user = request.user
    profile = UserProfile.objects.get(user=user)
    watchlist = Watchlist.objects.create(user=profile,series=tvseries,percent=0)
    success_url = '/dashboard/'
    return HttpResponseRedirect(success_url)


@login_required
def add_rate(request,id):
    if request.method=="GET":
        series = TVseries.objects.get(id=id)
        return render(request, './show/addrate.html', {'series':series})
    else:
        rating = request.POST.get('rating', '')
        tvseries = TVseries.objects.get(id=id)
        user = request.user
        profile = UserProfile.objects.get(user=user)
        series_rating = SeriesRating.objects.create(user=profile,series=tvseries,rating=rating)
        name = user.id
        series = tvseries.id
        rate = int(rating)
        rate = (rate-10)/10
        request = AddRating(name, series, rate ,cascade_create=True)
        client.send(request)
        success_url = '/dashboard/'
        return HttpResponseRedirect(success_url)

show/templates/show/index.html
<html>

<head>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>TV Series Recommendation System</title>
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style type="text/css">
    body {
      background-image: url(../../static/images/seriale.jpg);
      background-repeat: no-repeat;
      background-size: 87% 100%;
      overflow-x: hidden;
      overflow-y: hidden;
    }
  </style>


  <title></title>
</head>

<body>
  <div class="container text-center" style="position: absolute; margin-left: 692px;">
    <div class="row">
      <a href="/login/"><button class="btn btn-lg btn-primary" style="font-size: 30px;margin-left:-120px; height: 680px;">Proceed <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></button></a>
    </div>
  </div>
</body>

</html>

show/templates/show/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  <title>TV Series Recommendation System</title>
  <!-- Favicon -->
  <link href="{% static "./assets/img/brand/favicon.png" %}" rel="icon" type="image/png">
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <!-- Icons -->
  <link href="{% static "./assets/vendor/nucleo/css/nucleo.css" %}" rel="stylesheet">
  <link href="{% static "./assets/vendor/@fortawesome/fontawesome-free/css/all.min.css" %}" rel="stylesheet">
  <!-- Argon CSS -->
  <link type="text/css" href="{% static "/assets/css/argon.css" %}" rel="stylesheet">
</head>

<body class="bg-default">
  <div class="main-content">
    <!-- Navbar -->
    <nav class="navbar navbar-top navbar-horizontal navbar-expand-md navbar-dark">
      <div class="container px-4">
        <a class="navbar-brand" href="../index.html">
          <span style="font-size: 24px; font-weight: 700;">BingeIt</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-collapse-main">
          <!-- Collapse header -->
          <div class="navbar-collapse-header d-md-none">
            <div class="row">
              <div class="col-6 collapse-brand">
                <a href="../index.html">
                  <img src="{% static "/assets/img/brand/blue.png" %}">
                </a>
              </div>
              <div class="col-6 collapse-close">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                  <span></span>
                  <span></span>
                </button>
              </div>
            </div>
          </div>
          <!-- Navbar items -->
          <ul class="navbar-nav ml-auto">
            <!-- <li class="nav-item">
              <a class="nav-link nav-link-icon" href="../index.html">
                <i class="ni ni-planet"></i>
                <span class="nav-link-inner--text">Dashboard</span>
              </a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="{% url 'show:register' %}">
                <i class="ni ni-circle-08"></i>
                <span class="nav-link-inner--text">Register</span>
              </a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link nav-link-icon" href="../examples/login.html">
                <i class="ni ni-key-25"></i>
                <span class="nav-link-inner--text">Login</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="../examples/profile.html">
                <i class="ni ni-single-02"></i>
                <span class="nav-link-inner--text">Profile</span>
              </a>
            </li> -->
          </ul>
        </div>
      </div>
    </nav>
    <!-- Header -->
    <div class="header bg-gradient-primary py-7 py-lg-8">
      <div class="container">
        <!-- <div class="header-body text-center mb-7">
          <div class="row justify-content-center">
            <div class="col-lg-5 col-md-6">
              <h1 class="text-white">Welcome!</h1>
              <p class="text-lead text-light">Use these awesome forms to login or create new account in your project for free.</p>
            </div>
          </div>
        </div> -->
      </div>
      <div class="separator separator-bottom separator-skew zindex-100">
        <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
          <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
        </svg>
      </div>
    </div>
    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">
              <div class="text-muted text-center mt-2 mb-3"><small>Sign in with</small></div>
              <div class="btn-wrapper text-center">
                <!-- <a href="#" class="btn btn-neutral btn-icon">
                  <span class="btn-inner--icon"><img src="{% static "/assets/img/icons/common/github.svg" %}"></span>
                  <span class="btn-inner--text">Github</span>
                </a> -->
                <a href="#" class="btn btn-neutral btn-icon">
                  <span class="btn-inner--icon"><img src="{% static "/assets/img/icons/common/google.svg" %}"></span>
                  <span class="btn-inner--text">Google</span>
                </a>
              </div>
            </div>
            <div class="card-body px-lg-5 py-lg-5">
              <div class="text-center text-muted mb-4">
                <small>Or sign in with credentials</small>
              </div>
              <form method="POST" action="{% url 'show:login' %}" role="form">
                {% csrf_token %}
                <div class="form-group mb-3">
                  <div class="input-group input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                    </div>
                    <input class="form-control" placeholder="Username" type="text" name="username">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                    </div>
                    <input class="form-control" placeholder="Password" type="password" name="password">
                  </div>
                </div>
                <!-- <div class="custom-control custom-control-alternative custom-checkbox">
                  <input class="custom-control-input" id=" customCheckLogin" type="checkbox">
                  <label class="custom-control-label" for=" customCheckLogin">
                    <span class="text-muted">Remember me</span>
                  </label>
                </div> -->
                <div class="text-center">
                  <button type="submit" class="btn btn-primary my-4">Sign in</button>
                </div>
              </form>
            </div>
          </div>
          <!-- <div class="row mt-3">
            <div class="col-6">
              <a href="#" class="text-light"><small>Forgot password?</small></a>
            </div>
            <div class="col-6 text-right">
              <a href="#" class="text-light"><small>Create new account</small></a>
            </div>
          </div> -->
        </div>
      </div>
    </div>
  </div>
  <!-- Footer -->
  <!-- <footer class="py-5">
    <div class="container">
      <div class="row align-items-center justify-content-xl-between">
        <div class="col-xl-6">
          <div class="copyright text-center text-xl-left text-muted">
            &copy; 2018 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
          </div>
        </div>
        <div class="col-xl-6">
          <ul class="nav nav-footer justify-content-center justify-content-xl-end">
            <li class="nav-item">
              <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
            </li>
            <li class="nav-item">
              <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
            </li>
            <li class="nav-item">
              <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
            </li>
            <li class="nav-item">
              <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer> -->
  <!-- Argon Scripts -->
  <!-- Core -->
  <script src="{% static "/assets/vendor/jquery/dist/jquery.min.js" %}"></script>
  <script src="{% static "/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js" %}"></script>
  <script src="{% static "/assets/js/argon.js" %}"></script>

</body>

</html>

show/templates/show/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  <title>TV Series Recommendation System</title>
  <!-- Favicon -->
  <link href="{% static "./assets/img/brand/favicon.png" %}" rel="icon" type="image/png">
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <!-- Icons -->
  <link href="{% static "./assets/vendor/nucleo/css/nucleo.css" %}" rel="stylesheet">
  <link href="{% static "./assets/vendor/@fortawesome/fontawesome-free/css/all.min.css" %}" rel="stylesheet">
  <!-- Argon CSS -->
  <link type="text/css" href="{% static "/assets/css/argon.css" %}" rel="stylesheet">
</head>

<body class="bg-default">
  <div class="main-content">
    <!-- Navbar -->
    <nav class="navbar navbar-top navbar-horizontal navbar-expand-md navbar-dark">
      <div class="container px-4">
        <a class="navbar-brand" href="../index.html">
          <span style="font-size: 24px; font-weight: 700;">BingeIt</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-collapse-main">
          <!-- Collapse header -->
          <div class="navbar-collapse-header d-md-none">
            <div class="row">
              <div class="col-6 collapse-brand">
                <a href="../index.html">
                  <img src="{% static "/assets/img/brand/blue.png" %}">
                </a>
              </div>
              <div class="col-6 collapse-close">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                  <span></span>
                  <span></span>
                </button>
              </div>
            </div>
          </div>
          <!-- Navbar items -->
          <ul class="navbar-nav ml-auto">
            <!-- <li class="nav-item">
              <a class="nav-link nav-link-icon" href="../index.html">
                <i class="ni ni-planet"></i>
                <span class="nav-link-inner--text">Dashboard</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="../examples/register.html">
                <i class="ni ni-circle-08"></i>
                <span class="nav-link-inner--text">Register</span>
              </a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link nav-link-icon" href="{% url 'show:login' %}">
                <i class="ni ni-key-25"></i>
                <span class="nav-link-inner--text">Login</span>
              </a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link nav-link-icon" href="../examples/profile.html">
                <i class="ni ni-single-02"></i>
                <span class="nav-link-inner--text">Profile</span>
              </a>
            </li> -->
          </ul>
        </div>
      </div>
    </nav>
    <!-- Header -->
    <div class="header bg-gradient-primary py-7 py-lg-8">
      <div class="container">
        <!-- <div class="header-body text-center mb-7">
          <div class="row justify-content-center">
            <div class="col-lg-5 col-md-6">
              <h1 class="text-white">Welcome!</h1>
              <p class="text-lead text-light">Use these awesome forms to login or create new account in your project for free.</p>
            </div>
          </div>
        </div> -->
      </div>
      <div class="separator separator-bottom separator-skew zindex-100">
        <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
          <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
        </svg>
      </div>
    </div>
    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <!-- Table -->
      <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">
              <div class="text-muted text-center mt-2 mb-4"><small>Sign up with</small></div>
              <div class="text-center">
                <!-- <a href="#" class="btn btn-neutral btn-icon mr-4">
                  <span class="btn-inner--icon"><img src="../assets/img/icons/common/github.svg"></span>
                  <span class="btn-inner--text">Github</span>
                </a> -->
                <a href="#" class="btn btn-neutral btn-icon">
                  <span class="btn-inner--icon"><img src="{% static "/assets/img/icons/common/google.svg" %}"></span>
                  <span class="btn-inner--text">Google</span>
                </a>
              </div>
            </div>
            <div class="card-body px-lg-5 py-lg-5">
              <div class="text-center text-muted mb-4">
                <small>Or sign up with credentials</small>
              </div>
              <form role="form" method="POST" action="{% url 'show:register' %}">
                {% csrf_token %}
                <div class="form-group">
                  <div class="input-group input-group-alternative mb-3">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                    </div>
                    <input class="form-control" placeholder="First Name" type="text" name="fname">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group input-group-alternative mb-3">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                    </div>
                    <input class="form-control" placeholder="Last Name" type="text" name="lname">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group input-group-alternative mb-3">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-hat-3"></i></span>
                    </div>
                    <input class="form-control" placeholder="Username" type="text" name="username">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group input-group-alternative mb-3">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                    </div>
                    <input class="form-control" placeholder="Email" type="email" name="email">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                    </div>
                    <input class="form-control" placeholder="Password" type="password" name="password">
                  </div>
                </div>
                <!-- <div class="text-muted font-italic"><small>password strength: <span class="text-success font-weight-700">strong</span></small></div>
                <div class="row my-4">
                  <div class="col-12">
                    <div class="custom-control custom-control-alternative custom-checkbox">
                      <input class="custom-control-input" id="customCheckRegister" type="checkbox">
                      <label class="custom-control-label" for="customCheckRegister">
                        <span class="text-muted">I agree with the <a href="#!">Privacy Policy</a></span>
                      </label>
                    </div>
                  </div>
                </div> -->
                <div class="text-center">
                  <button type="submit" class="btn btn-primary mt-4">Create account</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Footer -->
  <!-- <footer class="py-5">
    <div class="container">
      <div class="row align-items-center justify-content-xl-between">
        <div class="col-xl-6">
          <div class="copyright text-center text-xl-left text-muted">
            &copy; 2018 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
          </div>
        </div>
        <div class="col-xl-6">
          <ul class="nav nav-footer justify-content-center justify-content-xl-end">
            <li class="nav-item">
              <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
            </li>
            <li class="nav-item">
              <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
            </li>
            <li class="nav-item">
              <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
            </li>
            <li class="nav-item">
              <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer> -->
  <!-- Argon Scripts -->
  <!-- Core -->
  <script src="{% static "/assets/vendor/jquery/dist/jquery.min.js" %}"></script>
  <script src="{% static "/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js" %}"></script>
  <script src="{% static "/assets/js/argon.js" %}"></script>
</body>

</html>